### ISSUE TITLE
1.19 tracking issue

### ISSUE THREAD

**Issue by misode** [misode/upgrader#21]
### Fixes to implement:
- [x] Convert `/locatebiome` command
- [x] Convert `/placefeature` command
- [x] Entity predicate changes: type_specific
- [x] Remove location condition from some advancements 
- [x] Remove biome category field
- [x] Add replaceable field to carvers 
- [x] Remove dimension seed fields
- [x] Disk features
- [x] Extract splines from terrain shaper to density functions
- [x] Convert slides to density functions
- [x] Copy sampling data to old_blended_noise ensity functions
- [ ] Game event renames
- [x] Rename glow_lichen feature type
- [x] Add field to leave_vine tree decorator
- [x] Add monster spawn fields to dimension type
